# running ubuntu for easier binunits installation
# thanks to https://github.com/lordmilko/i686-elf-tools
FROM ubuntu:latest 

WORKDIR /code

RUN apt-get update && apt-get install -y \
    git \
    wget \
    sudo \
    make \
    lsb-release \

